### PR TITLE
Add option --no-exit-first to disable pytest exit once failure detected

### PR DESCRIPTION
**Pull request by haroldrandom**

### CODE REVIEW

**Comment by qwordy** [comment]
--no-exit-first, is there any better name?

**Comment by haroldrandom** [comment]
> --no-exit-first, is there any better name?

The idea comes from pytest:
image

Do you have better idea?

**Comment by qwordy** [comment]
Why the default behavior is different between azdev and pytest?

**Comment by haroldrandom** [comment]
> Why the default behavior is different between azdev and pytest?

Our developer demand detail output for progress and exit once tests fail, so, I make the `-x` the default behavior.

**Comment by jiasli** [comment]
`-x` was added by #188.

**Pull request merged**
