### PR TITLE
Use pkginfo to query and dump metadata of Python Package

### PR DESCRIPTION
**Pull request by haroldrandom**

### CODE REVIEW

**Comment by jiasli** [comment]
I didn't seem to find the logic to dump metadata. Is it automated?

**Comment by haroldrandom** [comment]
> I didn't seem to find the logic to dump metadata. Is it automated?

It's here
https://github.com/Azure/azure-cli-dev-tools/blob/cb0349814fa3a32744af214a3e0e8607287104fc/azdev/operations/extensions/__init__.py#L242-L244

I use the returned value of pkginfo instead of the the old formate of metadata.json from wheel==0.30.0, for instance:
```
{'author': 'Matthew Booe',
 'author_email': 'mabooe@microsoft.com',
 'azext.isPreview': True,
 'azext.minCliCoreVersion': '2.2.0',
 'classifiers': ['Development Status :: 4 - Beta',
                 'Intended Audience :: Developers',
                 'Intended Audience :: System Administrators',
                 'Programming Language :: Python',
                 'Programming Language :: Python :: 2',
                 'Programming Language :: Python :: 2.7',
                 'Programming Language :: Python :: 3',
                 'Programming Language :: Python :: 3.5',
                 'Programming Language :: Python :: 3.6',
                 'Programming Language :: Python :: 3.7',
                 'Programming Language :: Python :: 3.8',
                 'License :: OSI Approved :: MIT License'],
 'home_page': 'https://github.com/Azure/azure-cli-extensions/tree/master/src/ai-examples',
 'license': 'MIT',
 'metadata_version': '2.0',
 'name': 'ai-examples',
 'platforms': ['UNKNOWN'],
 'summary': 'Add AI powered examples to help content.',
 'version': '0.2.0'}
```

**Comment by fengzhou-msft** [comment]
Just to confirm, this will require new extension packages to have a minimum core version of 2.5.0+?

**Comment by haroldrandom** [comment]
> Just to confirm, this will require new extension packages to have a minimum core version of 2.5.0+?

2.3.0+

**Pull request closed without merging**
