### PR TITLE
Pin pytest version to 6.0.2

### PR DESCRIPTION
**Pull request by qwordy**
Pytest 6.1.0 introduced breaking changes.
https://docs.pytest.org/en/stable/changelog.html#changelog
https://github.com/Azure/azure-cli-dev-tools/issues/261

### CODE REVIEW

**Comment by jiasli** [comment]
How is `azdev` affected? What are the symptoms?

**Comment by qwordy** [comment]
> 
> 
> How is `azdev` affected? What are the symptoms?

https://github.com/Azure/azure-cli-dev-tools/issues/261

**Review by yungezz — APPROVED** [review]

**Comment by haroldrandom** [comment]
why azure-cli 2.13.0 is still able to released?

**Comment by qwordy** [comment]
> 
> 
> why azure-cli 2.13.0 is still able to release?

Does the release pipeline use azdev?

**Comment by haroldrandom** [comment]
closed as CI is fine without this patch

**Pull request closed without merging**
