### PR TITLE
Linter Rule Updates. 

### PR DESCRIPTION
**Pull request by adewaleo**
See https://github.com/Azure/azure-cli/pull/8608

Allow parameter values that contain 'az' or pipes '|'. 
Lint nested commands.
Skip unsupported examples.

### CODE REVIEW

**Comment by tjprescott** [comment]
@adewaleo, this is failing CI. Please take a look.

**Comment by adewaleo** [comment]
Updates will be made to nested command parsing when #30 is addressed.

**Comment by adewaleo** [comment]
@tjprescott is this good to merge?

**Comment by tjprescott** [comment]
Thanks @adewaleo!

**Pull request merged**
